// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sentinel.EntityFrameworkCore;

#nullable disable

namespace Sentinel.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(SentinelSecurityDbContext))]
    [Migration("20260726212544_InitialSecurityDb")]
    partial class InitialSecurityDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("security_cache")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sentinel.EntityFrameworkCore.Models.DpopNonceEntry", b =>
                {
                    b.Property<string>("Thumbprint")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nonce");

                    b.HasKey("Thumbprint");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("dpop_nonce_store", "security_cache");
                });

            modelBuilder.Entity("Sentinel.EntityFrameworkCore.Models.JtiReplayCacheEntry", b =>
                {
                    b.Property<string>("Jti")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("jti_replay_cache", "security_cache");
                });

            modelBuilder.Entity("Sentinel.EntityFrameworkCore.Models.SessionBlacklistEntry", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("SessionId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("session_blacklist", "security_cache");
                });
#pragma warning restore 612, 618
        }
    }
}
