using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Npgsql;
using Sentinel.EntityFrameworkCore;
using Sentinel.EntityFrameworkCore.Extensions;
using Testcontainers.PostgreSql;

namespace Sentinel.Contracts.Postgres;

/// <summary>
///     Contract fixture: boots a REAL PostgreSQL 17 (the compose-pinned image
///     line) and wires the actual Sentinel.EntityFrameworkCore stores through their
///     public DI extension against it. The sql toolkit pinned here is the EF
///     Core Npgsql pipeline / compiled migrations — no re-implemented copies.
///
///     The default database is migrated in fixture startup so every suite gets a
///     ready schema; independent tests may spin fresh databases via
///     <see cref="FreshConnectionString"/>.
/// </summary>
public sealed class PostgreSqlContractFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres;

    public PostgreSqlContractFixture()
    {
        _postgres = new PostgreSqlBuilder("postgres:17-alpine")
            .WithDatabase("sentinel_contract")
            .WithUsername("contract_user")
            .WithPassword("contract_password")
            .Build();
    }

    /// <summary>Connection string of the migrated default database.</summary>
    public string ConnectionString { get; private set; } = string.Empty;

    public async ValueTask InitializeAsync()
    {
        await _postgres.StartAsync();
        ConnectionString = _postgres.GetConnectionString();

        await using var context = CreateContext(ConnectionString);
        await context.Database.MigrateAsync();
    }

    public async ValueTask DisposeAsync()
    {
        await _postgres.DisposeAsync();
    }

    /// <summary>
    ///     Returns a connection string to a NEW (currently non-existent)
    ///     database of the given name on the contract server.
    /// </summary>
    public string FreshConnectionString(string databaseName)
    {
        var builder = new NpgsqlConnectionStringBuilder(_postgres.GetConnectionString())
        {
            Database = databaseName
        };
        return builder.ToString();
    }

    /// <summary>Creates the named database (idempotently) and returns its connection string.</summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage(
        "Security", "CA2100",
        Justification = "Database name is a random GUID generated by the test (never user input); CREATE DATABASE does not support bound parameters.")]
    public async Task<string> CreateDatabaseAsync(string databaseName)
    {
        var admin = new NpgsqlConnectionStringBuilder(_postgres.GetConnectionString())
        {
            Database = "postgres"
        };

        await using var connection = new NpgsqlConnection(admin.ToString());
        await connection.OpenAsync();

        await using var command = connection.CreateCommand();
        command.CommandText = $"CREATE DATABASE \"{databaseName}\"" +
                              " TEMPLATE template0 ENCODING 'UTF8'";
        try
        {
            await command.ExecuteNonQueryAsync();
        }
        catch (PostgresException ex) when (ex.SqlState == "42P04")
        {
            // duplicate_database: created earlier by a previous run — reuse it.
        }

        return FreshConnectionString(databaseName);
    }

    public static SentinelSecurityDbContext CreateContext(string connectionString)
        => new(new DbContextOptionsBuilder<SentinelSecurityDbContext>()
            .UseNpgsql(connectionString)
            .Options);

    /// <summary>Builds a DI container with the REAL store registrations.</summary>
    public static ServiceProvider BuildProvider(string connectionString)
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddDbContextFactory<SentinelSecurityDbContext>(
            options => options.UseNpgsql(connectionString));
        services.AddEntityFrameworkSecurityCaches();
        return services.BuildServiceProvider();
    }
}

[CollectionDefinition(Name)]
public sealed class PostgreSqlContractCollection : ICollectionFixture<PostgreSqlContractFixture>
{
    public const string Name = "PostgreSQL Contract";
}