global using System.Diagnostics;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using Microsoft.IdentityModel.JsonWebTokens;
global using Microsoft.IdentityModel.Tokens;
global using Sentinel.Security.Abstractions.DPoP;
global using Sentinel.Security.Abstractions.Replay;
global using Sentinel.Security.Abstractions.Results;
